//Type
export const FETCH_STUDENTS = "student/FETCH_STUDENTS";
export const FETCH_STUDENTS_WITH_FILTER = "student/FETCH_STUDENTS_WITH_FILTER";
export const FETCH_STUDENT_DETAIL = "student/FETCH_STUDENT_DETAIL";
export const UPDATE_STUDENT = "student/UPDATE_STUDENT";
export const DELETE_STUDENT = "student/DELETE_STUDENT";

export const CLEAR_STUDENT_DETAIL = "student/CLEAR_STUDENT_DETAIL";