//Type
export const FETCH_PAYMENTS = "payment/FETCH_PAYMENTS";
export const FETCH_PAYMENTS_WITH_FILTER = "payment/FETCH_PAYMENTS_WITH_FILTER";
export const FETCH_PAYMENTS_BY_TUTOR_ID = "payment/FETCH_PAYMENTS_BY_TUTOR_ID";
export const FETCH_PAYMENT_DETAIL = "payment/FETCH_PAYMENT_DETAIL";
export const CREATE_PAYMENT = "payment/CREATE_PAYMENT";
export const UPDATE_PAYMENT = "payment/UPDATE_PAYMENT";
export const DELETE_PAYMENT = "payment/DELETE_PAYMENT";

export const CLEAR_PAYMENT_DETAIL = "admin/CLEAR_PAYMENT_DETAIL";