export { default as DeleteSyllabus } from "./action/DeleteSyllabus"
export { default as EditSyllabus } from "./action/EditSyllabus"
export { default as ViewSyllabus } from "./action/ViewSyllabus"
export { default as CreateSyllabus } from "./action/CreateSyllabus"
export { default as EditStatus } from "./action/EditStatus"