//Type
export const FETCH_SYLLABUSES = "syllabus/FETCH_SYLLABUSES";
export const FETCH_SYLLABUSES_WITH_FILTER = "syllabus/FETCH_SYLLABUSES_WITH_FILTER";
export const FETCH_SYLLABUS_DETAIL = "syllabus/FETCH_SYLLABUS_DETAIL";
export const CREATE_SYLLABUS = "syllabus/CREATE_SYLLABUS";
export const UPDATE_SYLLABUS = "syllabus/UPDATE_SYLLABUS";
export const DELETE_SYLLABUS = "syllabus/DELETE_SYLLABUS";

export const CLEAR_SYLLABUS_DETAIL = "admin/CLEAR_SYLLABUS_DETAIL";